name: Flask CI/CD Pipeline

on:
  push:
    branches:
      - staging   # Deploy to staging on pushes
      - main      # Only build & test on main push
  release:
    types: [published]  # Deploy to production on new release

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
         sudo apt update
         sudo apt install -y python3-pip
         sudo pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Build (package app)
        run: |
          echo "Building Flask app..."
          tar -czf flask_app.tar.gz *

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: flask_app
          path: flask_app.tar.gz

  deploy-staging:
    needs: build-test
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: flask_app

      - name: Deploy to Staging EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/flask-staging
            tar -xzf flask_app.tar.gz -C ~/flask-staging
            cd ~/flask-staging
            python3 -m venv venv
            ./venv/bin/pip install -r requirements.txt
            nohup ./venv/bin/python flask_app.py > app.log 2>&1 &

  deploy-production:
    needs: build-test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: flask_app

      - name: Deploy to Production EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p ~/flask-prod
            tar -xzf flask_app.tar.gz -C ~/flask-prod
            cd ~/flask-prod
            python3 -m venv venv
            ./venv/bin/pip install -r requirements.txt
            nohup ./venv/bin/python flask_app.py > app.log 2>&1 &
